In [1]:
# Import libraries
import numpy as np
import pandas as pd
import os.path
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
# Load the patient data
_data = np.load('data/re_intubation.npy', allow_pickle=True).tolist()
patients = _data['patients']
print("Loaded!")

Loaded!

In [7]:
# Select only true successful extubations and failures
success_bool = (patients['success']==True) & (patients['hospital_expire_flag']==0) # successful if never re-intubated and survived hospital stay
failure_bool = patients['failure']==True # failure if they were re-intubated within 48 hours
patients = patients[success_bool | failure_bool]

# Show some sample data
patients.head()

,subject_id,hadm_id,icustay_id,gender,dob,age,admittime,dischtime,intime,outtime,los,diagnosis,hospital_expire_flag,ventnum,success,failure
13875,27513,163557,200003,M,2151-04-17,48.29,2199-08-02 17:02:00,2199-08-22 19:00:00,2199-08-02 19:50:04,2199-08-08 17:09:18,5.8884,S/P RESECTION,0,1,True,False
11085,10950,189514,200006,M,2105-08-08,54.07,2159-09-03 11:27:00,2159-09-05 18:45:00,2159-09-03 11:28:14,2159-09-04 19:08:10,1.3194,TRACH OCCLUSION,0,1,True,False
14283,29904,129607,200009,F,2142-05-12,47.55,2189-11-30 10:45:00,2189-12-06 15:00:00,2189-11-30 10:34:32,2189-12-02 14:17:37,2.1549,"MITRAL REGURGITATION\MITRAL VALVE REPLACEMENT,...",0,1,True,False
11445,9514,127229,200014,M,2020-05-26,84.73,2105-02-16 23:15:00,2105-02-21 13:46:00,2105-02-16 23:16:48,2105-02-18 16:53:29,1.7338,ABDOMINAL AORTIC ANEURYSM,0,1,True,False
16349,61691,109307,200021,M,2054-02-18,60.85,2114-12-26 19:44:00,2114-12-28 18:30:00,2114-12-26 19:45:12,2114-12-27 22:46:28,1.1259,ALTERED MENTAL STATUS,0,1,True,False

In [17]:
# Print some statistics
print('Total number of patients: {}'.format(len(patients)))
print('Successful extubations: {} ({:.1f}%)'.format(sum(patients['success']), 100*sum(patients['success'])/len(patients)))
print('Extubation failures: {} ({:.1f}%)'.format(sum(patients['failure']), 100*sum(patients['failure'])/len(patients)))

Total number of patients: 14943
Successful extubations: 11695 (78.3%)
Extubation failures: 3248 (21.7%)